<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-KPO36PO" failures="0" tests="1" name="Grouping_Test" time="180.682" errors="0" timestamp="2024-09-25T12:05:05 IST">
  <testcase classname="testBase.BaseClass" name="@BeforeClass SetUp" time="180.438">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: &amp;apos;DESKTOP-KPO36PO&amp;apos;, ip: &amp;apos;10.11.12.104&amp;apos;">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'DESKTOP-KPO36PO', ip: '10.11.12.104'
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:563)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:245)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:152)
at testBase.BaseClass.SetUp(BaseClass.java:80)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.24.0', revision: '748ffc9bc3'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.2'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:418)
at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:374)
at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:54)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:89)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:61)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:53)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
... 30 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1956)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2091)
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:401)
... 40 more
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass SetUp -->
  <testcase classname="testBase.BaseClass" name="@AfterClass TearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterClass TearDown -->
  <testcase classname="testCases.TC02_LoginTest" name="verify_Login" time="0.001">
    <skipped/>
  </testcase> <!-- verify_Login -->
  <testcase classname="testCases.TC01_AccountRegistrationTest" name="Verify_Account_Registration" time="0.0">
    <ignored/>
  </testcase> <!-- Verify_Account_Registration -->
  <testcase classname="testCases.TC01_AccountRegistrationTest" name="Verify_Registration_Page" time="0.0">
    <ignored/>
  </testcase> <!-- Verify_Registration_Page -->
  <testcase classname="testCases.TC03_Login_DTT_Test" name="verify_Login_DTT" time="0.0">
    <ignored/>
  </testcase> <!-- verify_Login_DTT -->
</testsuite> <!-- Grouping_Test -->
